### ISSUE TITLE
Error when booting up Editor

### ISSUE THREAD

**Issue by fly-man-** [EriHoss/LibLSLCC#3]
* LSLCCEditor (1.5.0.0) x64 version

Exception Type:

System.Security.Principal.IdentityNotMappedException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

Stack Trace:

   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification, AccessRule rule, Boolean& modified)
   at System.Security.AccessControl.CommonObjectSecurity.AddAccessRule(AccessRule rule)
   at LSLCCEditor.MainWindow.CreateOpenTabPipeServer(String pipeName)
   at LSLCCEditor.MainWindow.StartOpenTabPipeServer()
   at LSLCCEditor.MainWindow.Initialize(Boolean newInstance, String[] args)
   at LSLCCEditor.MainWindow..ctor()

**Comment by EriHoss** [comment]
This is in part of the code that detects if the editor is open (when opening another file) and sends the running editor process the file info so that it can be opened in the main window under a new tab.

Does it happen every time you open the editor or just when clicking on a new file to open while it is running? (or not running, for example clicking a file on the desktop to start the program initially)

Also what version of windows are you on if you don't mind.

**Comment by EriHoss** [comment]
And by chance are you using windows in a language other than English?

**Comment by EriHoss** [comment]
Ah, I have a pretty good hunch about what is happening. 

Try this release and let me know if the editor will open without this error.

https://github.com/EriHoss/LibLSLCC/releases/tag/1.2.2.1

**Comment by fly-man-** [comment]
@EriHoss Indeed, using a different language for Windows

And the 1.2.2.1 release did fix the issue for me

**Comment by EriHoss** [comment]
> @EriHoss Indeed, using a different language for Windows
> 
> And the 1.2.2.1 release did fix the issue for me

Good to hear.

it probably couldn't resolve the strings "Users" and "SYSTEM" to an SSID because of the system language being different.

Gonna go ahead and close this, thank you for reporting it.
